config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :hosts, only: [:index, :show]
      get 'hosts/:id/latest_data', to: 'hosts#latest_data'
    end
  end
  resources :host_items, only: [:create, :destroy, :update]
  post 'schedule_collector_job', to: 'host_items#schedule_collector_job'
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about' , to: 'pages#about'
  get 'home'  , to: 'pages#home'
  get 'signup' , to: 'users#new'
  get 'new_host' , to: 'hosts#new'
  #post 'users', to: 'users#create'
  resources :users, except: [:new]
  resources :hosts, except: [:new]
  get 'login' , to: 'sessions#new'
  post 'login' , to: 'sessions#create'
  delete 'logout' , to: 'sessions#destroy'
  get 'forbidden' , to: 'pages#forbidden'
  #resources :actions, only: %i[index]
  get 'test_connection', to: 'remote_actions#test_connection'
  #post 'apply_remote_action', to: 'remote_actions#apply_remote_action'
  get 'apply_remote_action', to: 'remote_actions#apply_remote_action'
  get 'unassign_items', to: 'items#unassign_items'
  get 'triggers', to: 'host_items#triggers'
  get '/hosts/:id/latest_data', to: 'hosts#latest_data'
  resources :items
  resources :remote_actions
  resources :active_alerts
  get 'configuration', to: 'application#configuration'
  post 'save_configuration', to: 'application#save_configuration'
  get 'dashboard', to: 'pages#dashboard'
end

app/models/article.rb
class Article < ApplicationRecord
    
    validates :title, presence: true
    validates :description, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
    #No longer needed because we have before_action @article = Article.find(params[:id])
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    #No longer needed because we have 'before_action' @article = Article.new(article_params)

    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save 
        flash[:notice] = "Article was created successfully"
        redirect_to @article
   else
      render 'new'
   end
  end

    #respond_to do |format|
    #  if @article.save
    #    format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
    #    format.json { render :show, status: :created, location: @article }
    #  else
    #    format.html { render :new, status: :unprocessable_entity }
    #    format.json { render json: @article.errors, status: :unprocessable_entity }
    #  end
    #end
  

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
      #No longer needed because we have before_action @article = Article.find(params[:id])
    
    if @article.update(article_params)
          flash[:notice] = "Article was updated successfully"
          redirect_to @article
     else
        render 'edit'
     end
    #respond_to do |format|
    #  if @article.update(article_params)
    #    format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
    #    format.json { render :show, status: :ok, location: @article }
    #  else
    #    format.html { render :edit, status: :unprocessable_entity }
    #    format.json { render json: @article.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    #No longer needed because we have before_action @article = Article.find(params[:id])

    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="container">

<%= render 'shared/errors', obj: @article %>
  <div class = "row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @article) do |form| %>
        <div class="form-group row">
            <%= form.label :title , class: "col-2 col-form-label"%>
            <div class="col-10">
              <%= form.text_field :title , class: "form-control"%>
            </div>
        </div>
        
        <div class="form-group row">
          
            <%= form.label :description , class: "col-2 col-form-label"%>
            <div class="col-10">
            <%= form.text_area :description , rows: 2 ,class: "form-control"%>
          </div>
        </div>
  
    <div class="actions" >
      <%= form.submit class: "btn btn-outline-success" %>
      <%= link_to 'Back to articles', articles_path  , class: "btn btn-outline-primary "%> 

    </div>
  </div>
  <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h2 class="text-center mt-4">Editing Article</h2>

<%= render 'form'%>

<div class="row justify-content-center"><%= link_to 'Show', @article , class: "btn btn-primary text-white" %> </div>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="text-center mt-4">Articles</h2>

<table class="table table-sm table-dark">
  <thead>
    <tr>
      
      <th class="text-center" scope="col">Title</th>
      <th class="text-center" scope="col">Description</th>
      <th class="text-center" scope="col">Created at</th>
      <th class="text-center" scope="col">Last update</th>
      <th class="text-center" scope="col">Actions</th>
   
    </tr>
  </thead>
  <tbody class="text-center">
    <% @articles.each do |article| %>
      <% if article.title == "test_color" %>
        <tr>
          <td class="invalid"><%= article.title %></td>
          <td class="invalid"><%= article.description %></td>
          <td class="invalid"><%= time_ago_in_words(article.created_at) %></td>
          <td class="invalid"><%= time_ago_in_words(article.updated_at) %></td>
          <td>
          <%= link_to 'Show', article_path(article) , class: "btn btn-outline-success text-white" %>
          <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-warning text-white"%>
          <%= link_to 'Delete', article, method: :delete, class: "btn btn-outline-danger text-white" , data: { confirm: 'Are you sure you want to delete article '+article.title+'?' } %>
          </td>
        </tr>
      <% else %>
        <tr>
          <td ><%= article.title %></td>
          <td ><%= article.description %></td>
          <td ><%= time_ago_in_words(article.created_at) %></td>
          <td ><%= time_ago_in_words(article.updated_at) %></td>
          <td >
          <%= link_to 'Show', article_path(article) , class: "btn btn-outline-success text-white" %>
          <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-warning text-white"%>
          <%= link_to 'Delete', article, method: :delete, class: "btn btn-outline-danger text-white" , data: { confirm: 'Are you sure you want to delete article '+article.title+'?' } %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<div>
<%= link_to 'Create', new_article_path, class: "btn btn-success text-white" %>
<%= link_to 'Home', home_path , class: "btn btn-primary text-white" %>
</div>

app/views/articles/new.html.erb
<h2 class="text-center mt-4">New Article</h2>

<%= render 'form' %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID of article:</strong>
  <%= @article.id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<p>
  <strong>Last updated:</strong>
  <%= @article.updated_at %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Delete', article_path(@article) , method: :delete%> |
<%= link_to 'Back', articles_path %> | 