config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :hosts, only: [:index, :show]
      get 'hosts/:id/latest_data', to: 'hosts#latest_data'
    end
  end
  resources :host_items, only: [:create, :destroy, :update]
  post 'schedule_collector_job', to: 'host_items#schedule_collector_job'
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about' , to: 'pages#about'
  get 'home'  , to: 'pages#home'
  get 'signup' , to: 'users#new'
  get 'new_host' , to: 'hosts#new'
  #post 'users', to: 'users#create'
  resources :users, except: [:new]
  resources :hosts, except: [:new]
  get 'login' , to: 'sessions#new'
  post 'login' , to: 'sessions#create'
  delete 'logout' , to: 'sessions#destroy'
  get 'forbidden' , to: 'pages#forbidden'
  #resources :actions, only: %i[index]
  get 'test_connection', to: 'remote_actions#test_connection'
  #post 'apply_remote_action', to: 'remote_actions#apply_remote_action'
  get 'apply_remote_action', to: 'remote_actions#apply_remote_action'
  get 'unassign_items', to: 'items#unassign_items'
  get 'triggers', to: 'host_items#triggers'
  get '/hosts/:id/latest_data', to: 'hosts#latest_data'
  resources :items
  resources :remote_actions
  resources :active_alerts
  get 'configuration', to: 'application#configuration'
  post 'save_configuration', to: 'application#save_configuration'
  get 'dashboard', to: 'pages#dashboard'
end

app/models/host.rb
class Host < ApplicationRecord
    belongs_to :user
    has_many :host_items
    has_many :items, through: :host_items
    
    validates :hostname, presence: true, uniqueness: true
    validates :ip_address_or_fqdn, presence: true, uniqueness: true
    validates :user_to_connect, presence: true
    validates :password, presence: true
    validates :ssh_port, presence: true, numericality: { only_integer: true }

    def online?
        Host.find(self.id).online
        # read the online status from the host table
    end

    def init?
        Host.find(self.id).os.nil? 
    end

    def self.search(search)
        if search
            host = Host.find_by(hostname: search)
            if host
                self.where(hostname: host.hostname)
            else
                @hosts = Host.all
            end
        else
            @hosts = Host.all
        end

    end
end

app/controllers/api/v1/hosts_controller.rb
class Api::V1::HostsController < ApplicationController
  def index
    hosts = Host.all
    
    render :json => { :hosts => hosts.as_json(:except => [:password, :run_as_sudo, :ssh_port, :user_id, :assigned_items_host, :user_to_connect])}, status: 200
  end

  def show
    @host = Host.find_by(id: params[:id])
    if @host 
        #render json: @host, status:200, except: :password
        render :json => { :host => @host.as_json(:except => [:password, :run_as_sudo, :ssh_port, :user_id, :assigned_items_host, :user_to_connect])}, status: 200
    else
        render json: {error: "Host not found"}, status: 404
    end
  end

  def latest_data
    @host = Host.find_by(id: params[:id])
    if @host 
      latest_values={}
      #iterate to get all assigned items and create latest_values hash
      @host.assigned_items_host.each do |item_id|
        latest_values[Item.find(item_id).item_name] = HostItem.where(host_id: @host.id, item_id: item_id).last.value
        puts latest_values
      end
      if !latest_values.empty?
        render :json => { :host=>@host.hostname, :items => latest_values.as_json() }, status: 200
      else
        render json: {error: "No items assigned on this host"}, status: 404
      end
    else
      render json: {error: "No host found"}, status: 404
    end
  end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
    before_action :require_user
    before_action :set_host, only: %i[ show edit update destroy assigned_items latest_data]
    before_action :permit_edit_own_host_or_admin, only: [:edit, :update, :destroy]
    
    def assigned_items
        @items = @host.items
    end

    def new
        @host = Host.new
    end

    def create
        @host = Host.new(host_params)
        @host.user = current_user
        
        if @host.save
            flash[:notice] = "#{@host.hostname} created"
            # Add job for ping on each host creation
            # Save job to file schedule to be loaded in case of server restart
            job_name="ping_#{@host.hostname}"
            run_interval = '1m'
            scheduler_data = YAML.load(File.open(Rails.root.join('config', 'sidekiq_scheduler.yml')))
            if scheduler_data.include?(job_name) == false
                scheduler_data[job_name] = { 'every' => [run_interval], 'class' => 'PingJob', 'args' => [@host.id] }
                File.open(Rails.root.join('config', 'sidekiq_scheduler.yml'), 'w') do |f|
                    f.write(YAML.dump(scheduler_data))
                end
            end
            Sidekiq.set_schedule(job_name, { 'every' => [run_interval], 'class' => 'PingJob', 'args' => [@host.id] })
            redirect_to hosts_path
        else
            render 'new'
        end
        
    end

    def edit
        
    end

    def update
        
        #Ensure that if password field is empty the password will not be overwritten
        if @host.update(host_params.except(:password))
            if !host_params[:password].empty?
                @host.update(password: host_params[:password])
            end

            if host_params[:autopatch] == "1" && @host.online == true
                job_name="autopatch_#{@host.hostname}"
                run_interval = '1d'
                scheduler_data = YAML.load(File.open(Rails.root.join('config', 'sidekiq_scheduler.yml')))
                if scheduler_data.include?(job_name) == false
                    scheduler_data[job_name] = { 'every' => [run_interval], 'class' => 'AutopatchJob', 'args' => [@host.id] }
                    File.open(Rails.root.join('config', 'sidekiq_scheduler.yml'), 'w') do |f|
                        f.write(YAML.dump(scheduler_data))
                    end
                end
                Sidekiq.set_schedule(job_name, { 'every' => [run_interval], 'class' => 'AutopatchJob', 'args' => [@host.id] })
            else
                job_name="autopatch_#{@host.hostname}"
                scheduler_data = YAML.load(File.open(Rails.root.join('config', 'sidekiq_scheduler.yml')))
                scheduler_data.delete(job_name)
                File.open(Rails.root.join('config', 'sidekiq_scheduler.yml'), 'w') do |f|
                    f.write(YAML.dump(scheduler_data))
                end
                Sidekiq.remove_schedule(job_name)
            end
            flash[:notice] = "Host #{@host.hostname} was updated successfully"
            redirect_to @host
       else
          render 'edit'
       end

    end

    def index
        @hosts = Host.search(params[:search]).paginate(page: params[:page], per_page: 25)
        if !params[:search].nil? && @hosts.count != 1
            if !params[:search].empty?
                flash.now[:warn]="There is no host with this name"
            else
                redirect_to hosts_path
            end
        end

    end

    def search

    end

    def show
        #@host = Host.find(params[:id])
        assigned_items
    end

    def latest_data
        @host.assigned_items_host
        render json: @host.assigned_items_host
    end
    
    def destroy
        #No longer needed because we have before_action @article = Article.find(params[:id])
        scheduler_data = YAML.load(File.open(Rails.root.join('config', 'sidekiq_scheduler.yml')))
        job_name="ping_#{@host.hostname}"
        scheduler_data.delete(job_name)
        File.open(Rails.root.join('config', 'sidekiq_scheduler.yml'), 'w') do |f|
            f.write(YAML.dump(scheduler_data))
        end
        Sidekiq.remove_schedule(job_name)
        @host.destroy
        redirect_to hosts_path
      end
    

    def show_actions
        @remote_actions=RemoteAction.where(user_id: @host.user_id)
    end
    private
    def host_params
        #byebug
        params.require(:host).permit( :ip_address_or_fqdn, :hostname, :user_to_connect, :password, :ssh_port, :run_as_sudo, :autopatch, :search)
    end

    def permit_edit_own_host_or_admin
        #Add after correlation between hosts and users
        if current_user.id != @host.user_id && current_user.admin != true
            flash[:alert] = "You don't have rights to modify this host"
            redirect_to hosts_path
        end
    end

    def set_host
        @host = Host.find(params[:id])
    end
end

app/helpers/host_helper.rb
module HostHelper
    def assigned_items_for_current_host(host_id)
        
        @assigned_items = Array.new
        #https://stackoverflow.com/questions/12718759/ruby-on-rails-caching-variables
        #https://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html#method-i-fetch
        #Use Rails cache to fecth the data only when needed
        #@assigned_items=Rails.cache.fetch("assigned_items_for_host_#{host_id}") do
        
        Host.find(host_id).assigned_items_host.each do |assigned_item| @assigned_items<< [assigned_item, Item.find(assigned_item).item_name] end
       
       @assigned_items
   end


   def not_assigned_items_for_current_host(host_id)
        
    @not_assigned_items = Array.new
    
    Item.where.not(id: Host.find(host_id).assigned_items_host).each do |item| @not_assigned_items<<[item.id, item.item_name]  
        end

    @not_assigned_items
   end

   def jobs_to_schedule(host_id)
       
       @jobs_to_schedule = Array.new
       #https://stackoverflow.com/questions/12718759/ruby-on-rails-caching-variables
       #https://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html#method-i-fetch
       #Use Rails cache to fecth the data only when needed
       #@assigned_items=Rails.cache.fetch("assigned_items_for_host_#{host_id}") do
       @jobs_to_schedule=Rails.cache.fetch("jobs_to_schedule_for_host_#{host_id}") do
            scheduler_data = YAML.load(File.open(Rails.root.join('config', 'sidekiq_scheduler.yml')))  
            
            Host.find(host_id).assigned_items_host.each do |assigned_item| 
                job_name="job_for_item_" + assigned_item.to_s + "_on_host_" + host_id.to_s
                
                if !scheduler_data.include?(job_name) 
                    @jobs_to_schedule << [assigned_item, Item.find(assigned_item).item_name]
                     
                end
            end
            #byebug
            @jobs_to_schedule
        end
   end

   def jobs_scheduled?(host_id,item_id)
    
    @job_scheduled=Rails.cache.fetch("job_scheduled_for_item_#{item_id}_host_#{host_id}") do
        scheduler_data = YAML.load(File.open(Rails.root.join('config', 'sidekiq_scheduler.yml'))) 
        job_name="job_for_item_" + item_id.to_s + "_on_host_" + host_id.to_s
        @job_scheduled=scheduler_data.include?(job_name) 
        @job_scheduled
    end
    
   end


    
end

app/views/hosts/_form.html.erb
<div class="container-sm " >
    <%= render 'shared/errors', obj: @host %>
      <div class = "row justify-content-center ">
        <div class="col-sm-4 row-20 form_container">
          <%= form_with(model: @host) do |form| %>
            <div class="form-group  row-20 ">
                <strong><%= form.label :hostname , class: "col-2 col-form-label"%></strong>
                <div class="col-20">
                  <%= form.text_field :hostname , class: "form-control form-control-sm", placeholder: "Your hostname"%>
                </div>
            </div>
            
            <div class="form-group row-20">
              
              <strong><%= form.label "IP/FQDN" , class: "col-2 col-form-label text-uppercase"%></strong>
                <div class="col-20">
                <%= form.text_field :ip_address_or_fqdn ,class: "form-control form-control-sm", placeholder: "IP or FQDN of host"%>
              </div>
            </div>

            <div class="form-group row-20">
            <strong><%= form.label "Username" , class: "col-2 col-form-label"%></strong>
                <div class="col-20">
                <%= form.text_field :user_to_connect ,class: "form-control form-control-sm" , placeholder: "Username to connect to host"%>
                </div>
            </div>

            <div class="form-group row-20">
            <strong><%= form.label "Password" , class: "col-2 col-form-label"%></strong>
                <div class="col-20">
                <%= form.password_field :password ,class: "form-control form-control-sm" , placeholder: "Password to connect to host"%>
                </div>
            </div>
            
            <div style = "position:relative; left:20px; bottom:5px">
              <%= form.check_box :run_as_sudo, class: "form-check-input" %>
              <strong><%= form.label "Run as sudo?" , class: "form-check-label" %></strong>
            </div>

            <br>

            <div class="form-group row-20">
              <strong><%= form.label "Port" , class: "col-2 col-form-label"%></strong>
              
                <div class="col-20">
                <%= form.text_field :ssh_port ,class: "form-control form-control-sm" , placeholder: "SSH port to connect to host"%>
                </div>
            </div>
            <% if !@host.new_record? %>
            <div style = "position:relative; left:20px; bottom:5px">
              <%= form.check_box :autopatch, class: "form-check-input" %>
              <strong><%= form.label "Autopatch" , class: "form-check-label" %></strong>
            </div>
            <%end%>

        <div class="actions text-center" >
          <%= form.submit(@host.new_record? ? "Add new" : "Update", class: "btn btn-success") %>
    
        </div>
      </div>
      <% end %>
      </div>
    </div>

app/views/hosts/index.html.erb
<div id="page-content">
    <div class="container text-center">
    <h2 class="mt-4 animate-charcter" id="page-title">Hosts</h2>
    </div>
    
    
    <%= form_tag hosts_path, :method => 'get' , class:"form-inline" do %>
        <%= text_field_tag :search, params[:search], class: "form-control mr-sm-4-searchbox", placeholder: "Search hostname"%>
        <%= submit_tag "Search", :title => nil, class: "btn btn-success my-2 my-sm-0"%>
    <% end %>
      
    <br>
    <table class="table table-sm table-dark table-bordered ">
      <thead>
        <tr>
          
          <th class="text-center" scope="col">Hostname</th>
          <th class="text-center" scope="col">IP/FQDN</th>
          <th class="text-center" scope="col">Owner</th>
          <th class="text-center" scope="col">Status</th>
          <th class="text-center" scope="col">Actions</th>
       
        </tr>
      </thead>
      <tbody class="text-center">
        <% @hosts.each do |host| %>
          
            <tr>
              <td ><%= host.hostname %></td>
              <td ><%= host.ip_address_or_fqdn %></td>
              <td ><%= User.find_by(id: host.user_id).username %></td>
              <td >
                <% if host.online? %>
                  <span class="badge badge-success">Online</span>
                <% else %>
                  <% if host.init? %>
                  <span class="badge badge-info">Initializing</span>
                  <%else%>
                  <span class="badge badge-danger">Offline</span>
                  <% end %>
                <% end %>
                <% if host.reboot_required %>
                  <span class="badge badge-warning">Reboot</span>
                <%end%>
              </td>
              <td>
              <% if host.init? %>
                <%= link_to 'View', host_path(host) , class: "btn btn-outline-success text-white disabled" %>
              <%else%>
                <%= link_to 'View', host_path(host) , class: "btn btn-outline-success text-white" %>
              <%end%>
              <% if @current_user.id == host.user_id || @current_user.admin == true %>
                <%= link_to 'Edit', edit_host_path(host), class: "btn btn-outline-warning text-white"%>
                <%= link_to 'Delete', host, method: :delete, class: "btn btn-outline-danger text-white" , data: { confirm: 'Are you sure you want to delete '+host.hostname+'?' } %>
              <%else%>
                <%= link_to 'Edit', edit_host_path(host), class: "btn btn-outline-warning text-white disabled"%>
                <%= link_to 'Delete', host, method: :delete, class: "btn btn-outline-danger text-white disabled" , data: { confirm: 'Are you sure you want to delete '+host.hostname+'?' } %>
              <% end %>
              </td>
            </tr>
        <% end %>
      </tbody>
    </table>
    <%= render 'shared/pagination', obj: @hosts %>
      <div class="text-center">
      <%= link_to 'Create', new_host_path, class: "btn btn-success text-white" %>
      <%= link_to 'Home', root_path , class: "btn btn-primary text-white" %>
      </div>
</div>
    

app/views/hosts/show.html.erb
<div id="page-content">
  
  <h2 class="text-center mt-4">
    <%case @host.os.downcase %>
    <%when /ubuntu*/%>
      <img src="<%= asset_path('logo-ubuntu.png') %>" class="img-fluid mx-auto d-block" width=10% height=10%>
    <%when /centos*/%>
      <img src="<%= asset_path('logo-centos.png') %>" class="img-fluid mx-auto d-block" width=10% height=10%>
    <%when /windows*/%>
      <img src="<%= asset_path('logo-windows.png') %>" class="img-fluid mx-auto d-block" width=10% height=10%>
    <%when /redhat*/%>
      <img src="<%= asset_path('logo-redhat.png') %>" class="img-fluid mx-auto d-block" width=10% height=10%>
    <%when /fedora*/%>
      <img src="<%= asset_path('logo-fedora.png') %>" class="img-fluid mx-auto d-block" width=7% height=7%>
    <% else %>
      <img src="<%= asset_path('host_icon.png') %>" class="img-fluid mx-auto d-block" width="50" height="50">
    <% end %> 
    <%= @host.hostname %></h2>
    <h4 class="text-center mt-8" >
    <% if @host.online? %>
        <span class="badge badge-success">Online</span>
    <% else %>
        <span class="badge badge-danger">Offline</span>
    <% end %>
    </h4>
    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">

            <div class="card-body">
              <div class="card-text text-center font-weight-bold ">IP/FQDN: <%=  @host.ip_address_or_fqdn %> </div>
              <div class="card-text text-center font-weight-bold ">Owned by: <%=  User.find(@host.user_id).username %> </div>

              <div class="card-text text-center ">SSH user to connect: <%=  @host.user_to_connect%> </div>
              <div class="card-text text-center ">SSH port: <%=  @host.ssh_port %> </div>
              <div class="card-text text-center ">Run as sudo: <%=  @host.run_as_sudo %> </div>
              <% if @host.os != nil %>
                <div class="card-text text-center ">Operating system: <%=  @host.os %> </div>
              <% end %>
<!--          actions_array=Array.new
              <% #RemoteAction.where(user_id: @host.user_id).ids.each { |n|   actions_array.append(RemoteAction.find(n).action_name) } %>
-->
<!--              <%= form_with(url: apply_remote_action_path(:action_id,:host_id), method: :post, params: {format: @host_id}) do |form| %> 
                            send :id as params and list the name 
                <%= form.select :action_id , RemoteAction.where(user_id: @host.user_id).collect { |p| [  p.action_name , p.id] } %>
                <%= form.submit "Run" %>
              <%end%>
-->           
              <!--assigned_items_for_current_host is a host helper method that gets all the items assigned to host-->
              <% if !assigned_items_for_current_host(@host.id).blank?%>
                <%= form_with url: host_items_path, method: :post do  |form| %> 
                <%= form.select :item_id, (assigned_items_for_current_host(@host.id).collect{ |p| [p[1],p[0]] })%>
                  <%= hidden_field_tag(:host_id, @host.id) %>
                  <%= form.submit "Get assigned item now" %>
                <%end%>
              <%end%>

              <%= form_with url: host_items_path, method: :post do  |form| %> 
                <%= form.select :item_id , (not_assigned_items_for_current_host(@host.id).collect{ |p| [p[1],p[0]] })%>
                  <%= hidden_field_tag(:host_id, @host.id) %>
                  <%= form.submit "Add new item" %>
                <%end%>
              
              <% if !jobs_to_schedule(@host.id).blank?%>
                <%= form_with url: schedule_collector_job_path, method: :post do  |form| %> 
                  <%= form.select :item_id , (jobs_to_schedule(@host.id).collect{ |p| [p[1],p[0]] }) %>
                    <%= hidden_field_tag(:host_id, @host.id) %>
                    <%= form.submit "Create job for item" %>
                <%end%>
              <%end%>
          <div style="padding-bottom: 10px; padding-top: 15px; ">
          <% if !@items.blank? %>
            <table class="table table-hover">
              <thead class="table-info">
                <tr>
                  <th scope="col">Item name</th>
                  <th scope="col"></th>
                  <th scope="col">Job</th>
                  <th scope="col"></th>
                  <th scope="col">Last value</th>
                  <th scope="col"></th>
                  <th scope="col">Last read</th>
                  <th scope="col"></th>
                  <th scope="col"></th>
                </tr>
              </thead>
              
              <tbody>
                <% all_items = Item.all %>
                    <% all_items.each do |item| %>
                      <% if !HostItem.where(host_id: @host.id, item_id: item.id).blank? %>
                         <tr>
                          <th scope="row"><%= item.item_name %>           
                          </th>
                          <td></td>
                          <td>
                          <% if jobs_scheduled?(@host.id,item.id) %>
                            <span class="badge badge-pill badge-success">Yes</span>
                          <%else%>
                            <span class="badge badge-pill badge-danger">No</span>
                          <%end%></td>
                          
                          <td></td>
                          <td ><%= HostItem.where(host_id: @host.id, item_id: item.id).last.value %></td>
                          <td></td>
                          <td><%= HostItem.where(host_id: @host.id, item_id: item.id).last.created_at%></td>
                          <td> <%= link_to "Triggers", triggers_path(id: HostItem.where(host_id: @host.id, item_id: item.id).ids.last), class: "btn btn-sm btn-outline-primary" %></td>
                          <!--We will pass item id to HostItem destroy method so we could indetify all item values and delete all-->
                          <td><%= link_to "x", host_item_path(item_id: item.id), class: "btn-close btn-sm btn-danger", method: :delete, data: {confirm: "This will remove all data collected for this item. Are you sure?"} %></td>
                        </tr>
                      <% end %>
                    <% end %>
                </tbody>
              </table>
            </div>
              <%end%>
              <% if @current_user == User.find(@host.user_id) || @current_user.admin == true %>
                <%= link_to "Edit", edit_host_path(@host), class: "btn btn-outline-info" %>
                <%= link_to "Delete", host_path(@host), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
              <%else%>
                <%= link_to "Edit", edit_host_path(@host), class: "btn btn-outline-info disabled" %>
                <%= link_to "Delete", host_path(@host), class: "btn btn-outline-danger disabled", method: :delete, data: {confirm: "Are you sure?"} %>
              <% end %>
              <%= link_to "Test connection", test_connection_path(@host.id), method: :get, class: "btn btn-outline-success" %>
            </div>
            
            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(@host.created_at) %> ago, 
              edited <%= time_ago_in_words(@host.updated_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> 