config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :hosts, only: [:index, :show]
      get 'hosts/:id/latest_data', to: 'hosts#latest_data'
    end
  end
  resources :host_items, only: [:create, :destroy, :update]
  post 'schedule_collector_job', to: 'host_items#schedule_collector_job'
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about' , to: 'pages#about'
  get 'home'  , to: 'pages#home'
  get 'signup' , to: 'users#new'
  get 'new_host' , to: 'hosts#new'
  #post 'users', to: 'users#create'
  resources :users, except: [:new]
  resources :hosts, except: [:new]
  get 'login' , to: 'sessions#new'
  post 'login' , to: 'sessions#create'
  delete 'logout' , to: 'sessions#destroy'
  get 'forbidden' , to: 'pages#forbidden'
  #resources :actions, only: %i[index]
  get 'test_connection', to: 'remote_actions#test_connection'
  #post 'apply_remote_action', to: 'remote_actions#apply_remote_action'
  get 'apply_remote_action', to: 'remote_actions#apply_remote_action'
  get 'unassign_items', to: 'items#unassign_items'
  get 'triggers', to: 'host_items#triggers'
  get '/hosts/:id/latest_data', to: 'hosts#latest_data'
  resources :items
  resources :remote_actions
  resources :active_alerts
  get 'configuration', to: 'application#configuration'
  post 'save_configuration', to: 'application#save_configuration'
  get 'dashboard', to: 'pages#dashboard'
end

app/controllers/remote_actions_controller.rb
class RemoteActionsController < ApplicationController
    before_action :require_user
    before_action :set_action, only: %i[ show edit update destroy ]
    before_action :permit_edit_own_action_or_admin, only: [:edit, :update, :destroy]
    

    def new
        @remote_action = RemoteAction.new
    end

    def create
        @remote_action = RemoteAction.new(params.require(:remote_action).permit(:action_name, :command_or_script, :path_to_script, :script))
        @remote_action.user = current_user
        if @remote_action.save
            flash[:notice] = "#{@remote_action.action_name} created"
            redirect_to remote_actions_path
        else
            render 'new'
        end
        
    end

    def edit

    end

    def update
        if @remote_action.update(remote_action_params)
            flash[:notice] = "Action #{@remote_action.action_name} was updated successfully"
            redirect_to @remote_action
       else
          render 'edit'
       end

    end

    def index
        @remote_actions = RemoteAction.paginate(page: params[:page], per_page: 25)
    end


    def show

    end

    
    def destroy
    
        @remote_action.destroy
        redirect_to remote_actions_path
    end

    
    def test_connection
        
        host = Host.find(params[:format])
        
        begin
            Net::SSH.start(host.ip_address_or_fqdn, host.user_to_connect, :password => host.password, :port => host.ssh_port, non_interactive: true) do |ssh|
                
            end
        rescue Net::SSH::AuthenticationFailed
            flash[:warn] = "SSH authentiction failed. Check credentials!"
        rescue Errno::ECONNREFUSED
            flash[:warn] = "SSH connection refused"
        rescue Errno::EHOSTUNREACH
            @error = "Host unreacheable - no route to host"
        else
            flash[:notice] = "Connection succesfully"
        
        end
        redirect_to host
    end

    def apply_remote_action
        require "net/scp"
        @host = Host.find(params[:host_id])
        @remote_action = RemoteAction.find(params[:remote_action_id])
        begin
            if @remote_action.script 
                Net::SSH.start(@host.ip_address_or_fqdn, @host.user_to_connect, :password => @host.password, :port => @host.ssh_port, non_interactive: true) do |ssh|
                    if @host.run_as_sudo 
                        File.open("/tmp/deploy.file", "w") { |f| f.write "#{@remote_action.command_or_script}" }
                        sudo_pass="echo -e \"#{@host.password}\n\" | "
                        ssh.scp.upload!("/tmp/deploy.file", "#{@remote_action.path_to_script}")
                        ssh.exec! sudo_pass+"sudo -S chmod +x #{@remote_action.path_to_script}"
                        ssh.exec! sudo_pass+"sudo -S sed -i.bak s/\r//g #{@remote_action.path_to_script}"
                        output=(ssh.exec! sudo_pass+"sudo -S #{@remote_action.path_to_script}")
                    else
                        #ssh.exec! "touch #{@remote_action.path_to_script}"
                        #ssh.exec! "printf \"#{command}\" > #{@remote_action.path_to_script}"
                        #ssh.exec! "sed -i.bak s/\r//g #{@remote_action.path_to_script}"
                        #
                        File.open("/tmp/deploy.file", "w") { |f| f.write "#{@remote_action.command_or_script}" }
                        ssh.scp.upload!("/tmp/deploy.file", "#{@remote_action.path_to_script}")
                        ssh.exec! "chmod +x #{@remote_action.path_to_script}"
                        ssh.exec! "sed -i.bak s/\r//g #{@remote_action.path_to_script}"
                        output=(ssh.exec! "#{@remote_action.path_to_script}")
                    end
                    @message = "Command \"#{@remote_action.action_name}\" returned:\n" + output #@actions.script_content
                    if output.empty?
                        @message="Command produced no output"
                    end
                    respond_to do |format|
                        format.js { render partial: 'remote_actions/result' }
                    end
                end
                
            else
                Net::SSH.start(@host.ip_address_or_fqdn, @host.user_to_connect, :password => @host.password, :port => @host.ssh_port, non_interactive: true) do |ssh|
                    if @host.run_as_sudo 
                        sudo_pass="echo -e \"#{@host.password}\n\" | "
                        output=(ssh.exec! sudo_pass+"sudo -S "+@remote_action.command_or_script)
                        
                    else
                        output=(ssh.exec! @remote_action.command_or_script)
                    end
                    @message = "Command \"#{@remote_action.action_name}\" returned:\n" + output #@actions.script_content
                    if output.empty?
                        @message="Command produced no output"
                    end
                    respond_to do |format|
                        format.js { render partial: 'remote_actions/result' }
                    end
                   
                end
            end
        rescue Net::SSH::AuthenticationFailed
            respond_to do |format|
                flash.now[:alert] = "SSH authentiction failed. Check credentials!"
                format.js { render partial: 'remote_actions/result' }
            end

        rescue Errno::ECONNREFUSED
            respond_to do |format|
                flash.now[:alert] = "SSH connection refused"
                format.js { render partial: 'remote_actions/result' }
            end
        rescue Errno::EHOSTUNREACH
            respond_to do |format|
                flash.now[:alert] = "Host unreachable - No route to host"
                format.js { render partial: 'remote_actions/result' }
            end
        end
        
        #redirect_to @action #this keeps the same page but shows warn
        #render "remote_actions/show" #this renders the show view of remote_actions with the @message var 
      
    end
    
    private
    def remote_action_params
        params.require(:remote_action).permit(:action_name, :command_or_script, :path_to_script, :script)
    end

    def permit_edit_own_action_or_admin
        if current_user.id != @remote_action.user_id && current_user.admin != true
            flash[:alert] = "You don't have rights to modify this action"
            redirect_to remote_actions_path
        end
    end

    def set_action
        @remote_action = RemoteAction.find(params[:id])
    end

    
end

app/views/remote_actions/_form.html.erb
<div class="container-sm " >
    <%= render 'shared/errors', obj: @remote_action %>
      <div class = "row justify-content-center ">
        <div class="col-sm-4 row-20 form_container">
          <%= form_with(model: @remote_action) do |form| %>
            <div class="form-group  row-20 ">
                <strong><%= form.label :action_name , class: "col-20 col-form-label"%></strong>
                <div class="col-20">
                  <%= form.text_field :action_name , class: "form-control form-control-sm", placeholder: "Your action name"%>
                </div>
            </div>

            

            <div class="form-group row-20">
  
              <strong><%= form.label :command_or_script , class: "col-20 col-form-label"%></strong>
                <div class="col-20 ">
                  <%= form.text_area :command_or_script ,class: "form-control rounded-5 code-bg", placeholder: "Command or script to execute"%>
              </div>
            </div>
            <div   style="position:relative; left:20px; bottom:5px">
              <%= form.check_box :script ,id: "script_checkbox", class: "form-check-input" %>
              <strong><%= form.label :script , class: "form-check-label"  %></strong>
            </div>

          
            <div class="script_path_textbox">
              <div class="form-group row-20" >
              <strong><%= form.label :path_to_script , class: "col-20 col-form-label"%></strong>
                  <div class="col-20">
                  <%= form.text_field :path_to_script ,class: "form-control form-control-sm" , placeholder: "Path to create the script"%>
                  </div>
              </div>
            </div>

              <script type="text/javascript">
                //initial state 
                //.script_path_textbox is a class on the div for textbox
                //#script_checkbox is an id for the checkbox
                //jquery
                if ($("#script_checkbox").is(':checked')) {
                      $(".script_path_textbox").show();
                  } else {
                      $(".script_path_textbox").hide();
                  }
                $("#script_checkbox").click(function(){
                  if ($("#script_checkbox").is(':checked')) {
                      $(".script_path_textbox").show();
                  } else {
                      $(".script_path_textbox").hide();
                  }
                  
                });
              </script>

      
        <div class="actions text-center" >
          <%= form.submit(@remote_action.new_record? ? "Add new" : "Update", class: "btn btn-success")%>
    
        </div>
      </div>
      <% end %>
      </div>
    </div>

app/views/remote_actions/_result.html.erb
<div id="messages-content_js">
  
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %> 

</div>

<% if @message %>
    <textarea class="form-control rounded-5" id="exampleFormControlTextarea1 " rows="3"><%=  @message %></textarea>
<% end %>

app/views/remote_actions/_result.js.erb
document.querySelector('#results').innerHTML = '<%= escape_javascript(render "remote_actions/result.html") %>';

app/views/remote_actions/edit.html.erb
<div id="page-content">
    <h2 class="text-center mt-4">Edit <%= @remote_action.action_name %></h2>
    
    <%= render 'form' %>
</div>

app/views/remote_actions/index.html.erb
<div id="page-content">
    <div class="container text-center">
    <h2 class="mt-4 animate-charcter" id="page-title">Remote actions</h2>
    </div>
    
    <%= render 'shared/pagination', obj: @remote_actions %>

    <table class="table table-sm table-dark table-bordered ">
      <thead>
        <tr>
          
          <th class="text-center" scope="col">Action name</th>
          <th class="text-center" scope="col">Script</th>
          <th class="text-center" scope="col">Command</th>
          <th class="text-center" scope="col">Owner</th>
          <th class="text-center" scope="col">Actions</th>
       
        </tr>
      </thead>
      <tbody class="text-center">
        <% @remote_actions.each do |action| %>
          
            <tr>
              <td ><%= action.action_name %></td>
              <% if action.script == true %>
                <td >&#10004;</td>
                <td ></td>
              <%else %>
                <td ></td>
                <td >&#10004;</td>
              <%end%>
              <td ><%= User.find_by(id: action.user_id).username %></td>
              <td>

              <%= link_to 'View', remote_action_path(action) , class: "btn btn-outline-success text-white" %>
              <% if @current_user.id == action.user_id || @current_user.admin == true %>
                <%= link_to 'Edit', edit_remote_action_path(action), class: "btn btn-outline-warning text-white"%>
                <%= link_to 'Delete', action , method: :delete, class: "btn btn-outline-danger text-white" , data: { confirm: 'Are you sure you want to delete ?' } %>
              <% end %>
              </td>
            </tr>
        <% end %>
      </tbody>
    </table>
    <%= render 'shared/pagination', obj: @actions %>
    <div class="text-center">
    <%= link_to 'Create', new_remote_action_path, class: "btn btn-success text-white" %>
    <%= link_to 'Home', root_path , class: "btn btn-primary text-white" %>
    </div>
    </div>

app/views/remote_actions/new.html.erb
<div id="page-content">


    <h2 class="text-center mt-4">Create action</h2>
    
    <%= render 'form' %>
    
</div>

app/views/remote_actions/show.html.erb
<div id="page-content">
  
  <h2 class="text-center mt-4"><%= @remote_action.action_name %></h2>
    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <% if @current_user == User.find(@remote_action.user_id) || @current_user.admin == true %>
            <p>Apply on host:</p>
            <!--local: false enables javascript-->
            <%= form_with url: apply_remote_action_path, method: :get, local: false do  |form| %> 
                <!-- send :id as params and list the hostnames -->
                <% if current_user.admin == true %>
                  <%= form.select :host_id , Host.all.collect { |p| [  p.hostname , p.id] } %>
                <%else%>
                  <%= form.select :host_id , Host.where(user_id: current_user).collect { |p| [  p.hostname , p.id] } %>
                <%end%>
                  <!--add hiddent field tag to add extra parameter to params hash-->
                  <%= hidden_field_tag(:remote_action_id, @remote_action.id) %>
                  <%= form.submit "Apply" %>
                <%end%>
                <div id="results"></div>
                <!--<%= render 'remote_actions/result' %> -->

                <% if !@remote_action.script %>
                  <div class="card-body">
                    <div class="form-group">
                      <textarea class="form-control rounded-5 code-bg" id="exampleFormControlTextarea1" rows="1"><%=  @remote_action.command_or_script %></textarea>
                    </div>
                  <%else%>
                    <div class="card-body">
                      <div class="form-group">
                        <textarea class="form-control rounded-5 code-bg" id="exampleFormControlTextarea1" rows="20" ><%=  @remote_action.command_or_script %></textarea>
                    </div>
                  <%end%>
              <%else%>
                  <% if !@remote_action.script %>
                    <div class="card-body">
                      <div class="form-group">
                        <textarea class="form-control rounded-5 code-bg" id="exampleFormControlTextarea1" rows="1" readonly><%=  @remote_action.command_or_script %></textarea>
                    </div>
                  <%else%>
                    <div class="card-body">
                      <div class="form-group">
                        <textarea class="form-control rounded-5 code-bg" id="exampleFormControlTextarea1 formControlReadonly" rows="20" readonly><%=  @remote_action.command_or_script %></textarea>
                    </div>
                <%end%>

            <% end %>       

              <% if @current_user == User.find(@remote_action.user_id) || @current_user.admin == true %>
                <%= link_to "Edit", edit_remote_action_path(@remote_action), class: "btn btn-outline-info" %>
                <%= link_to "Delete", remote_action_path(@remote_action), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
              <% end %>
              <%= link_to "Back", remote_actions_path, class: "btn btn-outline-warning" %>
            </div>

            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(@remote_action.created_at) %> ago, 
              edited <%= time_ago_in_words(@remote_action.updated_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> 