config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :hosts, only: [:index, :show]
      get 'hosts/:id/latest_data', to: 'hosts#latest_data'
    end
  end
  resources :host_items, only: [:create, :destroy, :update]
  post 'schedule_collector_job', to: 'host_items#schedule_collector_job'
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about' , to: 'pages#about'
  get 'home'  , to: 'pages#home'
  get 'signup' , to: 'users#new'
  get 'new_host' , to: 'hosts#new'
  #post 'users', to: 'users#create'
  resources :users, except: [:new]
  resources :hosts, except: [:new]
  get 'login' , to: 'sessions#new'
  post 'login' , to: 'sessions#create'
  delete 'logout' , to: 'sessions#destroy'
  get 'forbidden' , to: 'pages#forbidden'
  #resources :actions, only: %i[index]
  get 'test_connection', to: 'remote_actions#test_connection'
  #post 'apply_remote_action', to: 'remote_actions#apply_remote_action'
  get 'apply_remote_action', to: 'remote_actions#apply_remote_action'
  get 'unassign_items', to: 'items#unassign_items'
  get 'triggers', to: 'host_items#triggers'
  get '/hosts/:id/latest_data', to: 'hosts#latest_data'
  resources :items
  resources :remote_actions
  resources :active_alerts
  get 'configuration', to: 'application#configuration'
  post 'save_configuration', to: 'application#save_configuration'
  get 'dashboard', to: 'pages#dashboard'
end

app/views/layouts/_messages.html.erb
<div id="messages-content">
  
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
          <%= msg%>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %> 
  
</div>

app/views/layouts/_navigation.html.erb
    <nav class="navbar navbar-expand-lg navbar navbar-dark navbar-default navbar-nav">
        <a class="navbar-brand" id= "logo" href="/" style="padding-left: 15px;">
          <div class="waviy">
            <span style="--i:1">O</span>
            <span style="--i:2">V</span>
            <span style="--i:3">E</span>
            <span style="--i:4">R</span>
            <span style="--i:5">W</span>
            <span style="--i:6">A</span>
            <span style="--i:7">T</span>
            <span style="--i:8">C</span>
            <span style="--i:9">h</span>
            </div>
        </a>
        <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <% if logged_in? %>
              <li class="nav-item" >
                <%= link_to "Dashboard", dashboard_path, class: "nav-link"%>
              </li>
              <%if current_user.admin == true || current_user.regular_user == true%> 
                <li class="nav-item">
                  <%= link_to "Users", users_path, class: "nav-link" %>
                </li>
              <%end%>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Hosts
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to "Create host", new_host_path, class: "dropdown-item" %>
                  
                  <%= link_to "View all hosts", hosts_path, class: "dropdown-item" %>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Help</a>
                </div>
              </li>

              <li class="nav-item">
                <%= link_to "Items", items_path, class: "nav-link" %>
              </li>
             
              <li class="nav-item">
                <%= link_to "Remote actions", remote_actions_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Alerts", active_alerts_path, class: "nav-link" %>
              </li>

              <li class="nav-item">
                <%= link_to "Configuration", configuration_path, class: "nav-link" %>
              </li>

              </ul>
              <li class="nav-item dropdown navbar-default navbar-nav" >
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Logged in as [<%= current_user.username %>]
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to "View profile", user_path(current_user), class: "dropdown-item" %>
                  
                  <%= link_to "Edit profile", edit_user_path(current_user), class: "dropdown-item" %>
                  
                </div>
              </li>
              
              <div>
                <%= link_to "LOGOUT", logout_path, method: :delete , class: "btn btn-outline-success text-white mr-sm-2 float-left" %>
              </div>

            <% else %>
              <li class="nav-item text-white" style="padding-top: 1%;">
              Check me on Github
              </li>
              <li class="nav-item">
              <a href="https://github.com/andreisolo0/Overwatch-IoT-Systems-Monitoring"><img src="<%= asset_path('github.jpg') %>" class="img-fluid d-block" width=7% height=7% style="padding-left: 1%;"></a>
              </li>
              <!--<li class="nav-item">
                <%= link_to "Features", about_path, class: "nav-link" %>
              </li>
              
              -->
              </ul>
              <%= link_to "SIGN UP", signup_path, class: "btn btn-outline-success btn text-white", style: "margin-right: 10px;" %>
              <%= link_to "LOGIN", login_path, class: "btn btn-outline-success text-white mr-sm-2" %>
            <% end %>

          </form>
         
        </div>
      </nav> <span class="badge badge-warning" style="">Notice: Currently running on Heroku, functionality is limited. All items, remote actions and hosts are provided as an example.</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overwatch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://kit.fontawesome.com/8066260b3f.js" crossorigin="anonymous"></script>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= javascript_include_tag "//www.google.com/jsapi" %>
    <%= yield %>
    <footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
    <div class="container text-center ">
      <small>Copyright asolomon &copy; Overwatch</small><br>
      <small>v1.0-beta</small>
    </div>
  </footer>
  </body>
  
</html>